import os
from flask import Flask, request, jsonify, send_from_directory, abort
from werkzeug.utils import secure_filename

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_DIR = os.path.join(BASE_DIR, 'static')
UPLOAD_DIR = os.path.join(BASE_DIR, 'tmp')

os.makedirs(UPLOAD_DIR, exist_ok=True)

app = Flask(__name__, static_folder=STATIC_DIR, static_url_path='')
app.config['UPLOAD_FOLDER'] = UPLOAD_DIR

# Optional basic auth for demo protection
DEMO_PASSWORD = os.environ.get('DEMO_BASIC_AUTH_PASSWORD')

def check_basic_auth():
    if not DEMO_PASSWORD:
        return True
    pw = request.args.get('pw') or request.form.get('pw')
    if pw == DEMO_PASSWORD:
        return True
    abort(403)

@app.route('/')
def index():
    # Serve the demo static page
    return send_from_directory(STATIC_DIR, 'index.html')

@app.route('/api/summary', methods=['POST'])
def summary():
    # minimal demo: accept text or file, return placeholder summary
    check_basic_auth()
    text = request.form.get('text', '')
    if 'file' in request.files:
        f = request.files['file']
        filename = secure_filename(f.filename)
        path = os.path.join(app.config['UPLOAD_FOLDER'], filename)
        f.save(path)
        # Demo mode won't run ASR. Return placeholder message.
        summary_text = f"Demo mode: received file '{filename}'. Real transcription not enabled in demo."
    elif text:
        summary_text = f"Demo mode summary for input text: {text[:200]}"
    else:
        return jsonify({'error': 'no input provided'}), 400

    response = {
        'title': 'Demo Title: Placeholder',
        'summary': summary_text,
        'key_points': [
            'Point 1 (demo)',
            'Point 2 (demo)'
        ],
        'social_copy': 'This is a demo social media caption generated by video-fast-summary.'
    }
    return jsonify(response)

if __name__ == '__main__':
    # Use environment PORT if provided
    port = int(os.environ.get('PORT', 8080))
    app.run(host='0.0.0.0', port=port, debug=True)
